# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# 导航栏头部名称
nav_name: 宙之眼

# 导航栏选项
# blank: 是否在新页面打开，默认 false
# children：开启二级导航栏
nav: 
  - 
    name: 主页
    path: /
  -
    name: 归档
    path: /archives/
  -
    name: 分类
    path: /categories/
  -
    name: 标签
    path: /tags/
  -
    name: 友链
    path: /friends/
  - 
    name: 关于
    path: /about/
  - 
    name: 抓到我
    children:
      -
        name: Github
        path: "https://github.com/lbinf"
        blank: true
      # -
      #   name: "知乎"
      #   path: "https://www.zhihu.com/people/godbmw/activities"
      #   blank: true

# 友链详细信息：支持多个友链

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# 是否开启 音乐组件
player: true

# 是否开启 分享功能: https://github.com/overtrue/share.js
social_share:
  enable: true
  sites: qzone, qq, weibo, wechat, douban, google, facebook, twitter
  disabled: 

# 是否开启 打赏功能
reward: 
  enable: true
  meta: 知识 & 情怀 | 二者兼得 # 提示文字
  button_meta: 打赏 # 按钮文字
  qrcodes: 
    # 支持多个支付方式
    # src: 二维码位置
    # meta: 二维码提示信息
    -
      src: /images/wechat.png 
      meta: "微信扫一扫, 支持一下"
    -
      src: /images/alipay.png
      meta: "支付宝扫一扫, 支付一下"

# 是否开启版权声明
# author: 您的名字
# license: 声明信息(支持html)
copyright: 
  enable: true
  author: leibinfeng 
  license: '本博客所有文章除特别声明外，均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> 许可协议。转载请注明出处！'

# 页脚信息 
# start: 建站时间. 格式：YYYY-MM-DD
# more: 自定义页脚信息(支持HTML)
footer: 
  start: '2018-02-10'
  more:
